### ISSUE TITLE
Parameter in overshoot logic is not used

### ISSUE THREAD

**Issue by franktegtmeyer** [Manuel83/craftbeerpi#24]
Maybe I just don't understand the code... But I expected to find the target temperature being altered by the parameter. Either up or down. But it seems not to be used at all.

**Comment by Manuel83** [comment]
Fixed in master!

**Comment by franktegtmeyer** [comment]
Code looks good. Will try it out next week.

**Comment by franktegtmeyer** [comment]
still not working... switches off at target temp with dev2.2
:-(

**Comment by franktegtmeyer** [comment]
btw: reopening of issues is not working... ;-)

**Comment by franktegtmeyer** [comment]
the logic IS working, but it looks like it took a restart of the running brew to change the settings.
I will open a new ticket for a better visualization of the running logic....
