### ISSUE TITLE
Prevent empty kettle name in setup

### ISSUE THREAD

**Issue by MrLeeh** [Manuel83/craftbeerpi#72]
Prevent the usage of an empty Kettle name field in the basic setup. Otherwise you won' t be able to modify the kettle later on as there is no link text to click on. You should check for a string length > 1 here. 

This isn' t a problem if you add a kettle in the "Kettle" menu. Here you already check for an empty name. Although it would be nice to get a message that the name is missing.

**Comment by Manuel83** [comment]
Fixed in Version 2.2.

**Comment by MrLeeh** [comment]
Just pulled the dev Version 2.2 and the error persists:

![image](https://cloud.githubusercontent.com/assets/4641542/17648697/080ebc32-621f-11e6-813b-fbdb237bb237.png)

**Comment by Manuel83** [comment]
You create the kettle during setup wizard right? That's what I can reproduce. 
If you create a kettle later it should not be possible to save the kettle with an empty name. 

Deactivated save button
![image](https://cloud.githubusercontent.com/assets/5859486/17648867/aafcf97c-6224-11e6-99b3-b324c134d835.png)

Activated save button
![image](https://cloud.githubusercontent.com/assets/5859486/17648869/c3f0b3e2-6224-11e6-8812-653028ee9974.png)

**Comment by MrLeeh** [comment]
Yes it is during setup wizard. Later it' s not possible to save the kettle.

**Comment by gimiki** [comment]
There is the same bug on "hardware configuration":
I can add any device with *no name* even if the save button is deactivated.

**Comment by Mrpond1970** [comment]
I found the same problem a while ago

 https://github.com/Manuel83/craftbeerpi/issues/98
